insert into authors (id, first_name, last_name) values (1, 'Joanne', 'Geockle');
insert into authors (id, first_name, last_name) values (2, 'Gail', 'Tott');
insert into authors (id, first_name, last_name) values (3, 'Christabella', 'Gehringer');
insert into authors (id, first_name, last_name) values (4, 'Janie', 'Maudsley');
insert into authors (id, first_name, last_name) values (5, 'Archer', 'Scoggins');
insert into authors (id, first_name, last_name) values (6, 'Merrill', 'Ridsdole');
insert into authors (id, first_name, last_name) values (7, 'Ginnifer', 'Kitcat');
insert into authors (id, first_name, last_name) values (8, 'Cristine', 'Titchen');
insert into authors (id, first_name, last_name) values (9, 'Henka', 'Feighry');
insert into authors (id, first_name, last_name) values (10, 'Irma', 'Stickford');
insert into authors (id, first_name, last_name) values (11, 'Cris', 'Tollow');
insert into authors (id, first_name, last_name) values (12, 'Clevey', 'Vernon');
insert into authors (id, first_name, last_name) values (13, 'Carey', 'Fullylove');
insert into authors (id, first_name, last_name) values (14, 'Kylie', 'Frankish');
insert into authors (id, first_name, last_name) values (15, 'Madlin', 'Gauler');
insert into authors (id, first_name, last_name) values (16, 'Manya', 'Brine');
insert into authors (id, first_name, last_name) values (17, 'Morley', 'Hanburry');
insert into authors (id, first_name, last_name) values (18, 'Ab', 'Bryan');
insert into authors (id, first_name, last_name) values (19, 'Bobbie', 'Maltman');
insert into authors (id, first_name, last_name) values (20, 'Nickola', 'Huton');
insert into authors (id, first_name, last_name) values (21, 'Jeannine', 'Folks');

insert into books (id, price, price_old, title, author_id) values (1, 1949, 2488, 'Solarbreeze', 3);
insert into books (id, price, price_old, title, author_id) values (2, 2698, 2848, 'Tempsoft', 5);
insert into books (id, price, price_old, title, author_id) values (3, 2058, 2981, 'Tin', 12);
insert into books (id, price, price_old, title, author_id) values (4, 1950, 3895, 'Konklab', 21);
insert into books (id, price, price_old, title, author_id) values (5, 693, 1995, 'Gembucket', 4);
insert into books (id, price, price_old, title, author_id) values (6, 506, 3272, 'Asoka', 20);
insert into books (id, price, price_old, title, author_id) values (7, 2418, 1244, 'Daltfresh', 15);
insert into books (id, price, price_old, title, author_id) values (8, 1901, 2840, 'Sonair', 19);
insert into books (id, price, price_old, title, author_id) values (9, 1581, 2545, 'Tampflex', 14);
insert into books (id, price, price_old, title, author_id) values (10, 2033, 3301, 'Otcom', 8);
insert into books (id, price, price_old, title, author_id) values (11, 2004, 1689, 'Zoolab', 2);
insert into books (id, price, price_old, title, author_id) values (12, 1652, 2580, 'Bamity', 10);
insert into books (id, price, price_old, title, author_id) values (13, 1566, 3433, 'Prodder', 16);
insert into books (id, price, price_old, title, author_id) values (14, 743, 1101, 'Pannier', 7);
insert into books (id, price, price_old, title, author_id) values (15, 2036, 2877, 'Stim', 13);
insert into books (id, price, price_old, title, author_id) values (16, 2156, 1622, 'Rank', 9);
insert into books (id, price, price_old, title, author_id) values (17, 2515, 1784, 'Latlux', 21);
insert into books (id, price, price_old, title, author_id) values (18, 2588, 3261, 'Lotlux', 6);
insert into books (id, price, price_old, title, author_id) values (19, 2793, 3293, 'Treeflex', 1);
insert into books (id, price, price_old, title, author_id) values (20, 1364, 1065, 'Voltsillam', 11);
insert into books (id, price, price_old, title, author_id) values (21, 1592, 2045, 'Home Ing', 8);
